[package]
name = "francis-scherm-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
framebuffer = { git = "https://github.com/Roysten/rust-framebuffer" }
actix-web = "4.0.0-rc.1"
